name: Salesforce CI/CD Workflow

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Salesforce CLI
        run: npm install --global sfdx-cli
      - name: Run Code Analyzer
        run: sfdx scanner:run --target force-app --format table
